version: 2

models:
  - name: raw_gz_sales
    description: sales details
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: date_date
        description: sales date
      - name: pdt_id
        description: product id 
      - name: revenue
        description: revenue
      - name: quantity
        description: quantity
  - name: raw_gz_product
    description: product details
    columns:
      - name: products_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: purchSE_PRICE
        description: purchase_price
  - name: raw_gz_ship
    description: ship details
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: shipping_fee
        description: shipping_fee
      - name: shipping_fee_1
        description: shipping_fee_1
      - name: logCost
        description: logCost
      - name: ship_cost
        description: ship_cost
        